# Copy these keys to .streamlit/secrets.toml and fill in real Spotify Web API credentials.

SPOTIPY_CLIENT_ID = "7490c6a9fe814bb094864868be8c116a"
SPOTIPY_CLIENT_SECRET = "d659347f2e4849b09fc06c7c52353013"
